USE bd_zenatu


DROP TABLE IF EXISTS DIM_CLIENTE
DROP TABLE IF EXISTS DIM_TIPO_VALOR
DROP TABLE IF EXISTS FATO_ASSINATURA
DROP TABLE IF EXISTS DIM_CONTATO
DROP TABLE IF EXISTS DIM_ENDERECO
DROP TABLE IF EXISTS DIM_ENCOMENDA
DROP TABLE IF EXISTS FATO_PEDIDO
DROP TABLE IF EXISTS DIM_PRODUTO


CREATE TABLE DIM_CLIENTE(
	ID_CLIENTE INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	ID_OPERACIONAL INT NOT NULL,
	CELULAR VARCHAR(13) NOT NULL,
	TELEFONE VARCHAR(13) NULL,
	EMAIL VARCHAR(50) NOT NULL,
	RUA VARCHAR(50) NOT NULL,
	NUMERO INT NOT NULL,
	REFERENCIA VARCHAR(50) NULL,
	CIDADE VARCHAR(50) NOT NULL,
	ESTADO VARCHAR(50) NOT NULL,
	UNIQUE (CPF)
) 


CREATE TABLE DIM_PRODUTO(
	ID_PRODUTO INT NOT NULL PRIMARY KEY,
	ID_OPERACIONAL INT NOT NULL,
	COD_PRODUTO INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	DATA_FABRICACAO DATETIME NOT NULL,
	DATA_VALIDADE DATETIME NOT NULL
)

CREATE TABLE DIM_TIPO_VALOR(
	ID_TIPO_VALOR INT NOT NULL PRIMARY KEY,
	TIPO_PACOTE VARCHAR(15) NOT NULL CHECK(TIPO_PACOTE IN ('1 POTE','3 POTES','5 POTES')),
	PRECO_PACOTE NUMERIC(10,2) NOT NULL
)

CREATE TABLE FATO_ASSINATURA(
    ID_ASSINATURA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    ID_OPERACIONAL INT NOT NULL,
    VALOR_MENSALIDADE DECIMAL(10,2) NOT NULL,
	MESES_ASSINATURA INT NULL,
    STATUS VARCHAR(9) NOT NULL CHECK (STATUS IN('ATIVO', 'CANCELADO')),
	ID_DATA_INICIO BIGINT NOT NULL REFERENCES DIM_TEMPO,
    ID_DATA_CANCELAMENTO BIGINT NULL REFERENCES DIM_TEMPO,
    ID_CLIENTE INT NOT NULL REFERENCES DIM_CLIENTE, --MUDEI AQUI
    ID_TIPO_VALOR INT NOT NULL REFERENCES DIM_TIPO_VALOR--MUDEI AQUI
)


CREATE TABLE FATO_PEDIDO(
	ID_PEDIDO INT NOT NULL PRIMARY KEY,
	ID_OPERACIONAL INT NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	ID_CLIENTE INT NOT NULL REFERENCES DIM_CLIENTE,
	ID_TIPO_VALOR INT NOT NULL REFERENCES DIM_TIPO_VALOR,
	ID_PRODUTO INT NOT NULL REFERENCES DIM_PRODUTO,
	ID_DATA_COMPRA  BIGINT NOT NULL REFERENCES DIM_TEMPO,
	ID_DATA_PREVISAO_CHEGADA BIGINT NOT NULL REFERENCES DIM_TEMPO,
	ID_DATA_CHEGADA BIGINT NOT NULL REFERENCES DIM_TEMPO,
	ID_CIDADE INT NOT NULL REFERENCES DIM_CLIENTE
)

SELECT * FROM DIM_CLIENTE
SELECT * FROM DIM_PRODUTO
SELECT * FROM DIM_TIPO_VALOR
SELECT * FROM DIM_TEMPO
SELECT * FROM FATO_ASSINATURA
SELECT * FROM FATO_PEDIDO


-- ETL STAGING AREA TO OLAP
-- CLIENTE
GO
CREATE OR ALTER PROCEDURE SP_ETL_CLIENTE(@DATA DATETIME)
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @DATA_CARGA DATETIME, @ID_CLIENTE INT, @NOME VARCHAR(50) NOT NULL,
	@CPF VARCHAR(11) NOT NULL,
	@ID_OPERACIONAL INT NOT NULL


	DECLARE  @NOME_TEMP VARCHAR(50) NOT NULL, @CPF_TEMP VARCHAR(11) NOT NULL,
	@ID_OPERACIONAL_TEMP INT NOT NULL,
	@CELULAR_TEMP VARCHAR(13) NOT NULL,
	@TELEFONE_TEMP VARCHAR(13) NULL,
	@EMAIL_TEMP VARCHAR(50) NOT NULL,
	@RUA_TEMP VARCHAR(50) NOT NULL,
	@NUMERO_TEMP INT NOT NULL,
	@REFERENCIA_TEMP VARCHAR(50) NULL,
	@CIDADE_TEMP VARCHAR(50) NOT NULL,
	@ESTADO_TEMP VARCHAR(50) NOT NULL

	DECLARE C_CLIENTE CURSOR
	FOR SELECT C.DATACARGA, C.COD_CLIENTE, C.NOME, C.CPF FROM TB_AUX_CLIENTE C

	OPEN C_CLIENTE
	FETCH C_CLIENTE INTO @DATA_CARGA, @ID_OPERACIONAL, @NOME, @CPF

	WHILE @@FETCH_STATUS = 0
	BEGIN
		-- VERIFY IF THE CLIENT NOT EXISTS IN THE OLAP THEN INSERT
		IF NOT EXISTS (SELECT * FROM DIM_CLIENTE WHERE ID_CLIENTE = @ID_OPERACIONAL)
		BEGIN
			INSERT INTO DIM_CLIENTE(NOME, CPF, ID_OPERACIONAL)
			VALUES(@NOME, @CPF, @ID_OPERACIONAL)	
		END
		-- IF THE CLIENT ALREADY EXISTS IN THE OLAP THEN 
		ELSE
		BEGIN
			-- GETTING THE OLDER VERSION OF CLIENTE
			SELECT @NOME_TEMP = C.NOME, @CPF_TEMP = C.CPF
			FROM DIM_CLIENTE C
			WHERE C.ID_OPERACIONAL = @ID_CLIENTE
			PRINT 'O CLIENTE ' + @NOME + ' JÁ EXISTE.'
		END
		FETCH C_CLIENTE INTO @DATA_CARGA, @ID_OPERACIONAL, @NOME, @CPF
	END
	CLOSE C_CLIENTE
	DEALLOCATE C_CLIENTE
END
GO