USE bd_zenatu

DROP TABLE IF EXISTS DIM_CONTATO
DROP TABLE IF EXISTS DIM_CLIENTE
DROP TABLE IF EXISTS DIM_ENDERECO
DROP TABLE IF EXISTS DIM_TIPO_VALOR
DROP TABLE IF EXISTS DIM_ENCOMENDA
DROP TABLE IF EXISTS FATO_ASSINATURA
DROP TABLE IF EXISTS FATO_PEDIDO
DROP TABLE IF EXISTS DIM_PRODUTO


CREATE TABLE DIM_CLIENTE(
	ID_CLIENTE INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	ID_OPERACIONAL INT NOT NULL
) 

CREATE TABLE DIM_CONTATO(
	ID_CLIENTE INT NOT NULL PRIMARY KEY REFERENCES DIM_CLIENTE,
	CELULAR VARCHAR(13) NOT NULL,
	TELEFONE VARCHAR(13) NULL,
	EMAIL VARCHAR(50) NOT NULL
)

CREATE TABLE DIM_ENDERECO(
	ID_CLIENTE INT NOT NULL PRIMARY KEY REFERENCES DIM_CLIENTE,
	RUA VARCHAR(50) NOT NULL,
	NUMERO INT NOT NULL,
	REFERENCIA VARCHAR(50) NULL,
	CIDADE VARCHAR(50) NULL,
	ESTADO VARCHAR(50) NULL
)

CREATE TABLE DIM_PRODUTO(
	ID_PRODUTO INT NOT NULL PRIMARY KEY,
	ID_OPERACIONAL INT NOT NULL,
	COD_PRODUTO INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	DATA_FABRICACAO DATETIME NOT NULL,
	DATA_VALIDADE DATETIME NOT NULL
)

CREATE TABLE DIM_TIPO_VALOR(
	ID_TIPO_VALOR INT NOT NULL PRIMARY KEY,
	TIPO_PACOTE VARCHAR(15) NOT NULL CHECK(TIPO_PACOTE IN ('1 POTE','3 POTES','5 POTES')),
	PRECO_PACOTE NUMERIC(10,2) NOT NULL
)

CREATE TABLE DIM_ENCOMENDA(
	ID_ENCOMENDA INT NOT NULL PRIMARY KEY,
	COD_ENCOMENDA INT NOT NULL,
	ID_OPERACIONAL INT NOT NULL,
	ID_PRODUTO INT REFERENCES DIM_PRODUTO,
	ID_TIPO_VALOR INT REFERENCES DIM_TIPO_VALOR
)

CREATE TABLE FATO_ASSINATURA(
    ID_ASSINATURA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    ID_OPERACIONAL INT NOT NULL,
    VALOR_MENSALIDADE DECIMAL(10,2) NOT NULL,
    STATUS VARCHAR(9) NOT NULL CHECK (STATUS IN('ATIVO', 'CANCELADO')),
	ID_DATA_INICIO BIGINT NOT NULL REFERENCES DIM_TEMPO,
    ID_DATA_CANCELAMENTO BIGINT NULL REFERENCES DIM_TEMPO,
    ID_CLIENTE INT NOT NULL, --MUDEI AQUI
    ID_TIPO_VALOR INT NOT NULL,--MUDEI AQUI
)


CREATE TABLE FATO_PEDIDO(
	ID_PEDIDO INT NOT NULL PRIMARY KEY,
	ID_OPERACIONAL INT NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	ID_CLIENTE INT NOT NULL REFERENCES DIM_CLIENTE,
	ID_TIPO_VALOR INT NOT NULL REFERENCES DIM_TIPO_VALOR,
	ID_ENCOMENDA INT NOT NULL REFERENCES DIM_ENCOMENDA,
	ID_PRODUTO INT NOT NULL REFERENCES DIM_PRODUTO,
	ID_DATA_COMPRA  BIGINT NOT NULL REFERENCES DIM_TEMPO,
	ID_DATA_PREVISAO_CHEGADA BIGINT NOT NULL REFERENCES DIM_TEMPO,
	ID_DATA_CHEGADA BIGINT NOT NULL REFERENCES DIM_TEMPO,
	ID_ENDEREÇO INT NOT NULL REFERENCES DIM_ENDERECO
)

SELECT * FROM DIM_CLIENTE
SELECT * FROM DIM_CONTATO
SELECT * FROM DIM_ENCOMENDA
SELECT * FROM DIM_ENDERECO
SELECT * FROM DIM_PRODUTO
SELECT * FROM DIM_TIPO_VALOR
SELECT * FROM FATO_ASSINATURA
SELECT * FROM FATO_PEDIDO
