use bd_zenatu

--CARREGANDO TB_AUX_CLIENTE
GO
CREATE OR ALTER PROCEDURE SP_STAGGING_CLIENTE (@DATACARGA DATETIME)
AS
BEGIN
	DELETE TB_AUX_CLIENTE
	WHERE DATACARGA = @DATACARGA

	INSERT INTO TB_AUX_CLIENTE(DATACARGA,COD_CLIENTE,NOME,CPF,ESTADO,CIDADE,RUA,NUMERO,REFERENCIA,CELULAR,TELEFONE,EMAIL)
	SELECT @DATACARGA, C.ID_CLIENTE,C.NOME,C.CPF,C.ESTADO,C.CIDADE,C.RUA,C.NUMERO,C.REFERENCIA,C.CELULAR,C.TELEFONE,C.EMAIL FROM TB_CLIENTE C
END


--CARREGANDO TB_AUX_PRODUTO
GO
CREATE OR ALTER PROCEDURE SP_STAGGING_PRODUTO (@DATACARGA DATETIME)
AS
BEGIN
	DELETE TB_AUX_PRODUTO
	WHERE DATACARGA = @DATACARGA

	INSERT INTO TB_AUX_PRODUTO(DATACARGA,COD_PRODUTO, MOME, DATA_FABRICACAO, DATA_VALIDADE)
	SELECT @DATACARGA, C.COD_PRODUTO, C.MOME, C.DATA_FABRICACAO, C.DATA_VALIDADE FROM TB_PRODUTO P
END


--CARREGANDO TB_AUX_TIPO_VALOR
GO
CREATE OR ALTER PROCEDURE SP_STAGGING_TIPO_VALOR (@DATACARGA DATETIME)
AS
BEGIN
	DELETE TB_AUX_TIPO_VALOR
	WHERE DATACARGA = @DATACARGA

	INSERT INTO TB_TIPO_VALOR(DATACARGA, ID_TIPO_VALOR, TIPO_PACOTE, PRECO_PACOTE)
	SELECT @DATACARGA, TP.ID_TIPO_VALOR, TP.TIPO_PACOTE, TP.PRECO_PACOTE FROM TB_TIPO_VALOR TP
END


--CARREGANDO TB_AUX_ASSINATURA
GO
CREATE OR ALTER PROCEDURE SP_STAGGING_ASSINATURA (@DATACARGA DATETIME)
AS
BEGIN
	DELETE TB_AUX_ASSINATURA
	WHERE DATACARGA = @DATACARGA



	INSERT INTO TB_AUX_PRODUTO(DATACARGA, COD_ASSINATURA, VALOR_MENSALIDADE, STATUS, ID_DATA_INICIO, ID_DATA_CANCELAMENTO, ID_CLIENTE, ID_TIPO_VALOR)
	SELECT '20191010', A.COD_ASSINATURA, A.VALOR_MENSALIDADE, A.STATUS, A.ID_DATA_INICIO, 
	A.ID_DATA_CANCELAMENTO, C.ID_CLIENTE, TP.ID_TIPO_VALOR FROM TB_ASSINATURA A
	INNER JOIN TB_PEDIDO P ON(A.ID_ASSINATURA=P.ID_ASSINATURA) INNER JOIN TB_CLIENTE C
	ON(P.ID_CLIENTE=C.ID_CLIENTE) INNER JOIN TB_TIPO_VALOR TV ON(P.ID_TIPO_VALOR=TV.TIPO_VALOR)
END