use bd_zenatu

DROP TABLE SP_STAGGING_CLIENTE
DROP TABLE SP_STAGGING_PRODUTO
DROP TABLE SP_STAGGING_TIPO_VALOR
DROP TABLE SP_STAGGING_ASSINATURA
DROP TABLE SP_STAGGING_PEDIDO

DROP PROCEDURE SP_STAGGING_CLIENTE
DROP PROCEDURE SP_STAGGING_PRODUTO
DROP PROCEDURE SP_STAGGING_TIPO_VALOR
DROP PROCEDURE SP_STAGGING_ASSINATURA
DROP PROCEDURE SP_STAGGING_PEDIDO

--CARREGANDO TB_AUX_CLIENTE
GO
CREATE PROCEDURE SP_STAGGING_CLIENTE (@DATACARGA DATETIME)
AS
BEGIN
	DELETE TB_AUX_CLIENTE
	WHERE DATACARGA = @DATACARGA

	INSERT INTO TB_AUX_CLIENTE(DATACARGA,COD_CLIENTE,NOME,CPF,ESTADO,CIDADE,RUA,NUMERO,REFERENCIA,CELULAR,TELEFONE,EMAIL)
	SELECT @DATACARGA, C.ID_CLIENTE,C.NOME,C.CPF,C.ESTADO,C.CIDADE,C.RUA,C.NUMERO,C.REFERENCIA,C.CELULAR,C.TELEFONE,C.EMAIL FROM TB_CLIENTE C
END


--CARREGANDO TB_AUX_PRODUTO
GO
CREATE PROCEDURE SP_STAGGING_PRODUTO (@DATACARGA DATETIME)
AS
BEGIN
	DELETE TB_AUX_PRODUTO
	WHERE DATACARGA = @DATACARGA

	INSERT INTO TB_AUX_PRODUTO(DATACARGA,COD_PRODUTO, NOME, DATA_FABRICACAO, DATA_VALIDADE)
	SELECT @DATACARGA, P.ID_PRODUTO, P.NOME, P.DATA_FABRICACAO, P.DATA_VALIDADE FROM TB_PRODUTO P
END


--CARREGANDO TB_AUX_TIPO_VALOR
GO
CREATE PROCEDURE SP_STAGGING_TIPO_VALOR (@DATACARGA DATETIME)
AS
BEGIN
	DELETE TB_AUX_TIPO_VALOR
	WHERE DATACARGA = @DATACARGA

	INSERT INTO TB_AUX_TIPO_VALOR(DATACARGA, ID_TIPO_VALOR, TIPO_PACOTE, PRECO_PACOTE)
	SELECT @DATACARGA, TP.ID_TIPO_VALOR, TP.TIPO_PACOTE, TP.PRECO_PACOTE FROM TB_TIPO_VALOR TP
END


--CARREGANDO TB_AUX_ASSINATURA
GO
CREATE PROCEDURE SP_STAGGING_ASSINATURA (@DATACARGA DATETIME)
AS
BEGIN
	DELETE TB_AUX_ASSINATURA
	WHERE DATACARGA = @DATACARGA
	   
	INSERT INTO TB_AUX_ASSINATURA(DATACARGA, COD_ASSINATURA, VALOR_MENSALIDADE, STATUS, DATA_INICIO, DATA_CANCELAMENTO, ID_CLIENTE, ID_TIPO_VALOR)
	SELECT @DATACARGA, A.ID_ASSINATURA, A.VALOR_MENSALIDADE, A.STATUS, A.DATA_INICIO, 
	A.DATA_CANCELAMENTO, P.ID_CLIENTE, P.ID_TIPO_VALOR FROM TB_ASSINATURA A
	INNER JOIN TB_PEDIDO P ON(A.ID_ASSINATURA=P.ID_ASSINATURA)
END


--CARREGANDO TB_AUX_PEDIDO
GO
CREATE PROCEDURE SP_STAGGING_PEDIDO (@DATACARGA DATETIME)
AS
BEGIN
	DELETE TB_AUX_PEDIDO
	WHERE DATACARGA = @DATACARGA

	DECLARE @ID_PEDIDO INT, @VALOR NUMERIC(10,2), @ID_CLIENTE INT, @ID_TIPO_VALOR INT, 
	@ID_PRODUTO INT, @ID_ASSINATURA INT, @DATA_COMPRA DATETIME, @DATA_PREVISAO_CHEGADA DATETIME, @DATA_CHEGADA DATETIME

	DECLARE C_PEDIDO CURSOR FOR SELECT P.ID_PEDIDO, P.VALOR, P.ID_CLIENTE, P.ID_TIPO_VALOR,
	P.ID_ASSINATURA, P.DATA_COMPRA, P.PREVISAO_CHEGADA, P.DATA_CHEGADA, P.ID_ENCOMENDA FROM TB_PEDIDO P
	
		OPEN C_PEDIDO 
		FETCH C_PEDIDO INTO @ID_PEDIDO, @VALOR, @ID_CLIENTE, @ID_TIPO_VALOR, @ID_ASSINATURA, @ID_ASSINATURA, @DATA_COMPRA, @DATA_PREVISAO_CHEGADA, @DATA_CHEGADA

		WHILE(@@FETCH_STATUS = 0)
		BEGIN
			DECLARE C_PRODUTO_PEDIDO CURSOR FOR SELECT PE.ID_PEDIDO, PE.ID_ENCOMENDA, E.ID_PRODUTO FROM TB_PEDIDO PE INNER JOIN TB_ENCOMENDA E
			ON (PE.ID_ENCOMENDA=E.ID_ENCOMENDA)
			WHERE @ID_PEDIDO = PE.ID_PEDIDO

			OPEN C_PRODUTO_PEDIDO
			FETCH C_PRODUTO_PEDIDO INTO @ID_PRODUTO

			WHILE(@@FETCH_STATUS = 0)
			BEGIN
				INSERT INTO TB_AUX_PEDIDO(DATACARGA, COD_PEDIDO, VALOR, ID_CLIENTE, ID_TIPO_VALOR, ID_PRODUTO, ID_ASSINATURA, DATA_COMPRA, DATA_PREVISAO_CHEGADA, DATA_CHEGADA)
				VALUES(@DATACARGA, @ID_PEDIDO, @VALOR, @ID_CLIENTE, @ID_TIPO_VALOR, @ID_PRODUTO, @ID_ASSINATURA, @DATA_COMPRA, @DATA_PREVISAO_CHEGADA, @DATA_CHEGADA)

				FETCH C_PRODUTO_PEDIDO INTO @ID_PRODUTO
			END
			CLOSE C_PRODUTO_PEDIDO
			DEALLOCATE C_PRODUTO_PEDIDO

			FETCH C_PEDIDO INTO @ID_PEDIDO, @VALOR, @ID_CLIENTE, @ID_TIPO_VALOR, @ID_ASSINATURA, @ID_ASSINATURA, @DATA_COMPRA, @DATA_PREVISAO_CHEGADA, @DATA_CHEGADA
		END
		CLOSE C_PEDIDO
		DEALLOCATE C_PEDIDO
END