use bd_zenatu

--CARREGANDO TB_AUX_CLIENTE
GO
CREATE OR ALTER PROCEDURE SP_STAGGING_CLIENTE (@DATACARGA DATETIME)
AS
BEGIN
	DELETE TB_AUX_CLIENTE
	WHERE DATACARGA = @DATACARGA

	INSERT INTO TB_AUX_CLIENTE(DATACARGA,COD_CLIENTE,NOME,CPF)
	SELECT @DATACARGA, C.ID_CLIENTE,C.NOME,C.CPF FROM TB_CLIENTE C
END



--CARREGANDO TB_AUX_CONTATO
GO
CREATE OR ALTER PROCEDURE SP_STAGGING_CONTATO (@DATACARGA DATETIME)
AS
BEGIN
	DELETE TB_AUX_CLIENTE
	WHERE DATACARGA = @DATACARGA

	INSERT INTO TB_AUX_CLIENTE(DATACARGA,COD_CLIENTE,NOME,CPF)
	SELECT @DATACARGA, C.ID_CLIENTE,C.NOME,C.CPF FROM TB_CLIENTE C
END



--CARREGANDO TB_AUX_ENDERECO
GO
CREATE OR ALTER PROCEDURE SP_STAGGING_ENDERECO (@DATACARGA DATETIME)
AS
BEGIN
	DELETE TB_AUX_CLIENTE
	WHERE DATACARGA = @DATACARGA

	INSERT INTO TB_AUX_CLIENTE(DATACARGA,COD_CLIENTE,NOME,CPF)
	SELECT @DATACARGA, C.ID_CLIENTE,C.NOME,C.CPF FROM TB_CLIENTE C
END