USE  bd_zenatu
DROP TABLE 

CREATE TABLE TB_AUX_CLIENTE(
	DATACARGA DATETIME NOT NULL,
	COD_CLIENTE INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	RUA VARCHAR(50) NOT NULL,
	NUMERO INT NOT NULL,
	REFERENCIA VARCHAR(50) NULL,
	CIDADE VARCHAR(50) NULL,
	ESTADO VARCHAR(50) NULL,
	CELULAR VARCHAR(13) NOT NULL,
	TELEFONE VARCHAR(13) NULL,
	EMAIL VARCHAR(50) NOT NULL
)

CREATE TABLE TB_AUX_PRODUTO(
	DATACARGA DATETIME NOT NULL,
	COD_PRODUTO INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	DATA_FABRICACAO DATETIME NOT NULL,
	DATA_VALIDADE DATETIME NOT NULL
)

CREATE TABLE TB_AUX_TIPO_VALOR(
	DATACARGA DATETIME NOT NULL,
	ID_TIPO_VALOR INT NOT NULL,
	TIPO_PACOTE VARCHAR(15) NOT NULL CHECK(TIPO_PACOTE IN ('1 POTE','3 POTES','5 POTES')),
	PRECO_PACOTE NUMERIC(10,2) NOT NULL
)

CREATE TABLE TB_AUX_ASSINATURA(
	DATACARGA DATETIME NOT NULL,
	COD_ASSINATURA INT NOT NULL,
	VALOR_MENSALIDADE DECIMAL(10,2) NOT NULL,
    STATUS VARCHAR(9) NOT NULL CHECK (STATUS IN('ATIVO', 'CANCELADO')),
	ID_DATA_INICIO BIGINT NOT NULL,
    ID_DATA_CANCELAMENTO BIGINT NULL,
    ID_CLIENTE INT NOT NULL, 
    ID_TIPO_VALOR INT NOT NULL,
	
)

CREATE TABLE TB_AUX_PEDIDO(
	DATACARGA DATETIME NOT NULL,
	COD_PEDIDO INT NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_TIPO_VALOR INT NOT NULL,
	ID_ENCOMENDA INT NOT NULL,
	ID_PRODUTO INT NOT NULL,
	ID_DATA_COMPRA  BIGINT NOT NULL,
	ID_DATA_PREVISAO_CHEGADA BIGINT NOT NULL,
	ID_DATA_CHEGADA BIGINT NOT NULL,
	ID_ENDEREÇO INT NOT NULL
)