CREATE DATABASE lab_casos_teste

use lab_casos_teste

--AMBIENTE OPERACIONAL
CREATE TABLE TB_FUNCIONARIO (
	MATRICULA INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(60) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	CARGO VARCHAR(50) NOT NULL,
	FUNCAO VARCHAR(50) NULL,
	SALARIO NUMERIC(10,2) NOT NULL,
	COD_SETOR INT NOT NULL REFERENCES TB_SETOR(COD_SETOR)
)

CREATE TABLE TB_SETOR (
	COD_SETOR INT NOT NULL PRIMARY KEY,
	NM_SETOR VARCHAR(50) NOT NULL,
	COD_DEPARTAMENTO INT NOT NULL REFERENCES
	TB_DEPARTAMENTO(COD_DEPARTAMENTO)
)

CREATE TABLE TB_DEPARTAMENTO (
	COD_DEPARTAMENTO INT NOT NULL PRIMARY KEY,
	NM_DEPARTAMENTO VARCHAR(50) NOT NULL
)



--Staging
CREATE TABLE TB_AUX_FUNCIONARIO (
	DATA_CARGA DATETIME NOT NULL,
	MATRICULA INT NOT NULL,
	NOME VARCHAR(60) NULL,
	CPF VARCHAR(11) NULL,
	CARGO VARCHAR(50) NULL,
	FUNCAO VARCHAR(50) NULL,
	SALARIO NUMERIC(10,2) NULL,
	CODIGO_SETOR INT NULL,
	SETOR VARCHAR(50) NULL,
	CODIGO_DEPARTAMENTO INT NULL,
	DEPARTAMENTO VARCHAR(50) NULL
)



--Dimensional
CREATE TABLE DIM_FUNCIONARIO (
	ID_FUNCIONARIO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MATRICULA INT NOT NULL,
	NOME VARCHAR(60) NULL,
	CPF VARCHAR(11) NULL,
	CARGO VARCHAR(50) NULL,
	FUNCAO VARCHAR(50) NULL,
	SALARIO NUMERIC(10,2) NULL,
	CODIGO_SETOR INT NULL,
	SETOR VARCHAR(50) NULL,
	CODIGO_DEPARTAMENTO INT NULL,
	DEPARTAMENTO VARCHAR(50) NULL,
	DT_INICIO DATETIME NOT NULL,
	DT_FIM DATETIME NULL,
	FL_CORRENTE VARCHAR(3) NOT NULL CHECK (FL_CORRENTE IN ('SIM','NAO'))
)


--INSERCAO AMBIENTE OLTP

	INSERT INTO TB_DEPARTAMENTO(COD_DEPARTAMENTO, NM_DEPARTAMENTO)
	VALUES (1,'PEOPLEOPS'), (2,'INFRAESTRUTURA'), (3,'TECNICA')

	INSERT INTO TB_SETOR(COD_SETOR, NM_SETOR, COD_DEPARTAMENTO)
	VALUES (1,'CONSULTORIA TECNICA',3), (2,'RESPOSTA A INCIDENTES',3),
	(3,'GERENCIAMENTO DE DISPOSITIVOS',3),(4,'CULTURA',1),(5,'RH',1),
	(6, 'FACILITIES',2)

	INSERT INTO TB_FUNCIONARIO(MATRICULA, NOME, CPF, CARGO, FUNCAO, SALARIO, COD_SETOR)
	VALUES (10, 'THIAGO', '067.XXXXX.X', 'ESTAGIARIO', 'SHADOW', 200.45, 1),
	(20, 'MF', '445.XXXXX.X', 'ESTAGIARIO', 'ESTAGIARIO SENIOR', 250.55, 1)





SELECT * FROM TB_FUNCIONARIO
SELECT * FROM TB_SETOR
SELECT * FROM TB_DEPARTAMENTO


-- 1
CREATE OR ALTER PROCEDURE SP_STAGGING_FUNCIONARIO (@DATACARGA DATETIME)
AS
BEGIN

--APAGANDO TUDO DO STAGING
DELETE FROM TB_AUX_FUNCIONARIO;

DECLARE @MATRICULA_OLTP INT, @NOME_OLTP VARCHAR(60),
		@CPF_OLTP VARCHAR(11), @CARGO_OLTP VARCHAR(50), @FUNCAO_OLTP VARCHAR(50),
		@SALARIO_OLTP NUMERIC(10,2), @CODIGO_SETOR_OLTP INT, @SETOR_OLTP VARCHAR(50),
		@CODIGO_DEPARTAMENTO_OLTP INT, @DEPARTAMENTO_OLTP VARCHAR(50)

DECLARE C_FUNCIONARIO CURSOR FOR SELECT F.MATRICULA, F.NOME, F.CPF, F.CARGO,
F.FUNCAO, F.SALARIO, F.COD_SETOR, S.NM_SETOR, D.COD_DEPARTAMENTO, D.NM_DEPARTAMENTO 
FROM TB_FUNCIONARIO F INNER JOIN TB_SETOR S
ON (F.COD_SETOR = S.COD_SETOR) INNER JOIN TB_DEPARTAMENTO D 
ON(S.COD_DEPARTAMENTO = D.COD_DEPARTAMENTO)

	OPEN C_FUNCIONARIO
	FETCH C_FUNCIONARIO INTO @MATRICULA_OLTP, @NOME_OLTP, @CPF_OLTP,
	@CARGO_OLTP, @FUNCAO_OLTP, @SALARIO_OLTP, @CODIGO_SETOR_OLTP,
	@SETOR_OLTP, @CODIGO_DEPARTAMENTO_OLTP, @DEPARTAMENTO_OLTP

	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		INSERT INTO TB_AUX_FUNCIONARIO(
		DATA_CARGA,	MATRICULA, NOME, CPF, CARGO, FUNCAO, SALARIO,
		CODIGO_SETOR, SETOR, CODIGO_DEPARTAMENTO, DEPARTAMENTO
		)
		VALUES(@DATACARGA,@MATRICULA_OLTP, @NOME_OLTP, @CPF_OLTP, @CARGO_OLTP,
		@FUNCAO_OLTP, @SALARIO_OLTP, @CODIGO_SETOR_OLTP, @SETOR_OLTP, 
		@CODIGO_DEPARTAMENTO_OLTP, @DEPARTAMENTO_OLTP)
	
		FETCH C_FUNCIONARIO INTO @MATRICULA_OLTP, @NOME_OLTP, @CPF_OLTP,
		@CARGO_OLTP, @FUNCAO_OLTP, @SALARIO_OLTP, @CODIGO_SETOR_OLTP,
		@SETOR_OLTP, @CODIGO_DEPARTAMENTO_OLTP, @DEPARTAMENTO_OLTP
	END
	CLOSE C_FUNCIONARIO
	DEALLOCATE C_FUNCIONARIO
END

DECLARE @DATACARGA DATETIME
SET @DATACARGA = GETDATE()

EXEC SP_STAGGING_FUNCIONARIO @DATACARGA


SELECT * FROM TB_AUX_FUNCIONARIO






--2
CREATE OR ALTER PROCEDURE SP_DIM_FUNCIONARIO
AS
BEGIN

--APAGANDO O HISTORICO DOS ATRIBUTOS QUE SÃO DO TIPO 1
--DELETE FROM DIM_FUNCIONARIO;

DECLARE @MATRICULA_STG INT, @NOME_STG VARCHAR(60),
		@CPF_STG VARCHAR(11), @CARGO_STG VARCHAR(50), @FUNCAO_STG VARCHAR(50),
		@SALARIO_STG NUMERIC(10,2), @CODIGO_SETOR_STG INT, @SETOR_STG VARCHAR(50),
		@CODIGO_DEPARTAMENTO_STG INT, @DEPARTAMENTO_STG VARCHAR(50), 
		@DT_INICIO DATETIME, @DT_FIM DATETIME, @FL_CORRENTE VARCHAR(3)


DECLARE C_AUX_FUNCIONARIO CURSOR FOR SELECT DATA_CARGA,	MATRICULA, NOME,
		CPF, CARGO, FUNCAO, SALARIO, CODIGO_SETOR,SETOR, CODIGO_DEPARTAMENTO,
		DEPARTAMENTO FROM TB_AUX_FUNCIONARIO

	OPEN C_AUX_FUNCIONARIO
	FETCH C_AUX_FUNCIONARIO INTO @DT_INICIO, @MATRICULA_STG, @NOME_STG, @CPF_STG,
	@CARGO_STG, @FUNCAO_STG, @SALARIO_STG, @CODIGO_SETOR_STG,
	@SETOR_STG, @CODIGO_DEPARTAMENTO_STG, @DEPARTAMENTO_STG

	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		

		IF EXISTS (SELECT 1 FROM DIM_FUNCIONARIO WHERE MATRICULA=@MATRICULA_STG)
		BEGIN
			UPDATE DIM_FUNCIONARIO
			SET NOME=@NOME_STG, CPF=@CPF_STG, CARGO=@CARGO_STG
			WHERE MATRICULA=@MATRICULA_STG
			IF
			BEGIN
				--FAZER AQUI
			END

		END

		--ELSE
		--BEGIN
		INSERT INTO DIM_FUNCIONARIO(
		MATRICULA, NOME, CPF, CARGO, FUNCAO, SALARIO,
		CODIGO_SETOR, SETOR, CODIGO_DEPARTAMENTO, DEPARTAMENTO,
		DT_INICIO, DT_FIM, FL_CORRENTE
		)
		VALUES(@MATRICULA_STG, @NOME_STG, @CPF_STG,
		@CARGO_STG, @FUNCAO_STG, @SALARIO_STG, @CODIGO_SETOR_STG,
		@SETOR_STG, @CODIGO_DEPARTAMENTO_STG, @DEPARTAMENTO_STG,
		GETDATE()
		)
		--END
		
		SET @DT_FIM = GETDATE()


	

	DT_INICIO DATETIME NOT NULL,
	DT_FIM DATETIME NULL,
	FL_CORRENTE VARCHAR(3) NOT NULL CHECK (FL_CORRENTE IN ('SIM','NAO'))




		FETCH C_AUX_FUNCIONARIO INTO @MATRICULA_STG, @NOME_STG, @CPF_STG,
		@CARGO_STG, @FUNCAO_STG, @SALARIO_STG, @CODIGO_SETOR_STG,
		@SETOR_STG, @CODIGO_DEPARTAMENTO_STG, @DEPARTAMENTO_STG
	END
	CLOSE C_FUNCIONARIO
	DEALLOCATE C_FUNCIONARIO
END



DELETE FROM DIM_FUNCIONARIO;