use bd_zenatu

DROP TABLE DIM_CLIENTE
DROP TABLE DIM_PRODUTO
DROP TABLE DIM_TIPO_VALOR
DROP TABLE FATO_ASSINATURA
DROP TABLE FATO_PEDIDO


CREATE TABLE DIM_CLIENTE(
	ID_CLIENTE INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	ID_OPERACIONAL INT NOT NULL,
	CELULAR VARCHAR(13) NOT NULL,
	TELEFONE VARCHAR(13) NULL,
	EMAIL VARCHAR(50) NOT NULL,
	RUA VARCHAR(50) NOT NULL,
	NUMERO INT NOT NULL,
	REFERENCIA VARCHAR(50) NULL,
	CIDADE VARCHAR(50) NOT NULL,
	ESTADO VARCHAR(50) NOT NULL,
	UNIQUE (CPF)
) 


CREATE TABLE DIM_PRODUTO(
	ID_PRODUTO INT NOT NULL PRIMARY KEY,
	ID_OPERACIONAL INT NOT NULL,
	COD_PRODUTO INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	DATA_FABRICACAO DATETIME NOT NULL,
	DATA_VALIDADE DATETIME NOT NULL
)

CREATE TABLE DIM_TIPO_VALOR(
	ID_TIPO_VALOR INT NOT NULL PRIMARY KEY,
	TIPO_PACOTE VARCHAR(15) NOT NULL CHECK(TIPO_PACOTE IN ('1 POTE','3 POTES','5 POTES')),
	PRECO_PACOTE NUMERIC(10,2) NOT NULL
)

CREATE TABLE FATO_ASSINATURA(
    ID_ASSINATURA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    ID_OPERACIONAL INT NOT NULL,
    VALOR_MENSALIDADE DECIMAL(10,2) NOT NULL,
	MESES_ASSINATURA INT NULL,
    STATUS VARCHAR(9) NOT NULL CHECK (STATUS IN('ATIVO', 'CANCELADO')),
	ID_DATA_INICIO BIGINT NOT NULL REFERENCES DIM_TEMPO,
    ID_DATA_CANCELAMENTO BIGINT NULL REFERENCES DIM_TEMPO,
    ID_CLIENTE INT NOT NULL REFERENCES DIM_CLIENTE, --MUDEI AQUI
    ID_TIPO_VALOR INT NOT NULL REFERENCES DIM_TIPO_VALOR --MUDEI AQUI
)

CREATE TABLE FATO_PEDIDO(
	ID_PEDIDO INT NOT NULL PRIMARY KEY,
	ID_OPERACIONAL INT NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	ID_CLIENTE INT NOT NULL REFERENCES DIM_CLIENTE,
	ID_TIPO_VALOR INT NOT NULL REFERENCES DIM_TIPO_VALOR,
	ID_PRODUTO INT NOT NULL REFERENCES DIM_PRODUTO,
	ID_DATA_COMPRA  BIGINT NOT NULL REFERENCES DIM_TEMPO,
	ID_DATA_PREVISAO_CHEGADA BIGINT NOT NULL REFERENCES DIM_TEMPO,
	ID_DATA_CHEGADA BIGINT NOT NULL REFERENCES DIM_TEMPO,
	ID_CIDADE INT NOT NULL REFERENCES DIM_CLIENTE
)

SELECT * FROM DIM_CLIENTE
SELECT * FROM DIM_PRODUTO
SELECT * FROM DIM_TIPO_VALOR
SELECT * FROM DIM_TEMPO
SELECT * FROM FATO_ASSINATURA
SELECT * FROM FATO_PEDIDO



