USE bd_zenatu

DROP TABLE DIM_TEMPO

DROP PROCEDURE sp_povoar_dim_tempo


CREATE TABLE DIM_TEMPO (
ID_TEMPO BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
NIVEL VARCHAR(8) NOT NULL CHECK (NIVEL IN ('DIA','MES','ANO')),
DATA DATETIME NULL,
DIA INT  NULL,
DIA_SEMANA VARCHAR(50)  NULL,
FIM_SEMANA VARCHAR(3)  NULL CHECK (FIM_SEMANA IN ('SIM','NAO')),
MES INT  NULL,
NOME_MES VARCHAR(100)  NULL,
TRIMESTRE INT  NULL,
NOME_TRIMESTRE VARCHAR(100)  NULL,
SEMESTRE INT  NULL,
NOME_SEMESTRE VARCHAR(100)  NULL,
ANO INT NOT NULL
)

--POVOAMENTO DA DIMENSÃO TEMPO

go
CREATE PROCEDURE sp_povoar_dim_tempo (@DT_INICIAL DATE, @DT_FINAL DATE)
AS
BEGIN
SET NOCOUNT ON
DECLARE @DIA INT,
@MES INT,
@ANO INT,
@TRIMESTRE INT,
@NOME_TRIMESTRE VARCHAR(100),
@SEMESTRE INT,
@NOME_SEMESTRE VARCHAR (100),
@FINALSEMANA CHAR(3),
@DATA DATE,
@NOMEDIA VARCHAR(7),
@DIASEMANA INT,
@NOME_DIA VARCHAR (7),
@NOME_MES VARCHAR(10),
@DATA_NIVEL DATETIME,
@ULTIMO_DIA_MES INT

SET @DATA = @DT_INICIAL

WHILE @DATA <= @DT_FINAL
BEGIN

SET @DIA = DAY(@DATA)
SET @MES = MONTH(@DATA)
SET @ANO = YEAR (@DATA)
SET @DIASEMANA = DATEPART(WEEKDAY, @DATA)
SET @TRIMESTRE = DATEPART(QUARTER, @DATA)
SET @NOME_DIA = DATENAME(dw, @DATA)
SET @NOME_MES = DATENAME(mm,@DATA)
SET @DATA_NIVEL =(SELECT DATEADD(DD, - DAY (DATEADD(M, 1, @DATA)),
 DATEADD(M, 1, @DATA)))
SET @ULTIMO_DIA_MES = DATEPART(DAY,@DATA_NIVEL)
IF @MES > 6
SET @SEMESTRE = 2
ELSE
SET @SEMESTRE = 1

IF @DIASEMANA = 7 OR @DIASEMANA = 1
SET @FINALSEMANA = 'SIM'
ELSE
SET @FINALSEMANA = 'NAO'

SET @NOME_SEMESTRE = STR(@SEMESTRE) + '° SEMESTRE' + '/' + STR(@ANO)
SET @NOME_TRIMESTRE = STR(@TRIMESTRE) + '° TRIMESTRE' + '/' + STR(@ANO)

INSERT INTO DIM_TEMPO(NIVEL, DATA, DIA, DIA_SEMANA,NOME_MES,
FIM_SEMANA, MES, TRIMESTRE,NOME_TRIMESTRE, SEMESTRE, NOME_SEMESTRE, ANO)
VALUES('DIA',@DATA, @DIA, @NOME_DIA,@NOME_MES, @FINALSEMANA,
@MES,@TRIMESTRE, @NOME_TRIMESTRE, @SEMESTRE, @NOME_SEMESTRE, @ANO)

IF (@DIA = DATEPART(DAY, @DATA_NIVEL))
BEGIN
INSERT INTO DIM_TEMPO(NIVEL,DATA, NOME_MES, MES, TRIMESTRE,NOME_TRIMESTRE, SEMESTRE,NOME_SEMESTRE, ANO)
VALUES('MES',@DATA, @NOME_MES, @MES, @TRIMESTRE, @NOME_TRIMESTRE, @SEMESTRE, @NOME_SEMESTRE , @ANO)
END
IF (@DIA = 31 AND @MES = 12)
BEGIN
INSERT INTO DIM_TEMPO(NIVEL,DATA, ANO)
VALUES('ANO',@DATA, @ANO)
END

SET @DATA = DATEADD(DAY, 1, @DATA)
END
END
go


EXEC sp_povoar_dim_tempo '20210101','20220101'
select * from DIM_TEMPO